tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: Install Frontend and Backend dependencies
    init: |
      cd /workspace/aws-bootcamp-cruddur/backend-flask
      pip3 install -r requirements.txt
      cd /workspace/aws-bootcamp-cruddur/frontend-react-js
      npm i
vscode:
  extensions:
    - 42Crunch.vscode-openapi
